name: cicd deployment with params

on: 
  workflow_dispatch:
    inputs:
      host:
        type: choice
        description: 'host to deploy'     
        required: true
        options:
          - HOST1
          - HOST2
      key:
        type: choice
        description: 'key for the host'     
        required: true
        options:
          - KEY1
          - KEY2

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.nodeversion }}
      - name: npm install and build
        run: |
          npm install

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ github.event.inputs.host == 'HOST1' && secrets.HOST1 || secrets.HOST2 }}
          key: ${{ github.event.inputs.key == 'KEY1' && secrets.KEY1 || secrets.KEY2 }}
          username: ${{ secrets.USER}}
          port: ${{ secrets.PORT}}
          script: |
            cd ~/cicd
            git pull origin main
            npm install
            pm2 restart cicd
