name: cicd deployment host-1

on: 
  workflow_dispatch

jobs: 
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.nodeversion }}
      - name: ssh deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST1}}
          key: ${{ secrets.KEY1}}
          username: ${{ secrets.USER}}
          port: ${{ secrets.PORT}}
          script: |
            cd ~/cicd
            echo -e "TEST1=santosh\nTEST2=rajesh" >> .env
            git pull origin main
            npm install 
            pm2 restart cicd
