name: cicd deployment with params

on: 
  workflow_dispatch:
    inputs:
      host:
        type: choice
        description: 'host to deploy'     
        required: true
        options:
          - HOST1
          - HOST2
      key:
        type: choice
        description: 'key for the host'     
        required: true
        options:
          - KEY1
          - KEY2

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.nodeversion }}
      - name: npm install and build
        run: |
          npm install

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - id: host
        run: export HOST=${{ github.event.inputs.host }} && echo "::set-output name=hostValue::${HOST}"
      - id: key
        run: export KEY=${{ github.event.inputs.key }} && echo "::set-output name=keyValue::${KEY}"
      - name: ssh deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets[steps.host.outputs.hostValue] }}
          key: ${{ secrets[steps.key.outputs.keyValue] }}
          username: ${{ secrets.USER1 }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/cicd
            git pull origin main
            npm install
            pm2 restart cicd
